version: '3.7'

services:
  drone-server:
    image: drone/drone:${DRONE_TAG_SERVER}
    container_name: drone-server
    restart: always
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    networks:
      - drone-network
    volumes:
      - ${DRONE_DATAS}:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_LETS_ENCRYPT=true
        #    stdin_open: true
        #    tty: true
        #    entrypoint: ["/bin/sh"]

  drone-agent:
    image: drone/agent:${DRONE_TAG_AGENT}
    container_name: drone-agent
    command: agent
    restart: always
    depends_on:
      - drone-server
    networks:
      - drone-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}

networks:
  drone-network:
    name: drone
    driver: bridge

