version: '2.1'
services:
  nginx_reverse:
    image: nginx
    container_name: nginx_reverse
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${NGINX_REVERSE_ROOT_DATAS_NGINXPROXY_CONF_D}:/etc/nginx/conf.d
      - ${NGINX_REVERSE_ROOT_DATAS_NGINXPROXY_CERTS}:/etc/nginx/certs
      - ${NGINX_REVERSE_ROOT_DATAS_NGINXPROXY_VHOST_D}:/etc/nginx/vhost.d
      - ${NGINX_REVERSE_ROOT_DATAS_USR_SHARE_NGINX_HTML}:/usr/share/nginx/html
    networks:
      - nginxReverse

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    depends_on:
      - nginx_reverse
    command: -notify-sighup nginx_reverse -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx_reverse
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${NGINX_REVERSE_ROOT_DATAS_NGINXPROXY_CONF_D}/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    networks:
      - nginxReverse

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
    depends_on:
      - docker-gen
    volumes_from:
      - nginx_reverse
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginxReverse

  httpd:
    image: httpd
    container_name: httpd
    depends_on:
      - nginx_reverse
      - docker-gen
      - nginx-proxy-letsencrypt
    environment:
      - VIRTUAL_HOST=httpd.doryhub.com
      - LETSENCRYPT_HOST=httpd.doryhub.com
      - LETSENCRYPT_EMAIL=garfield_trump@yahoo.com
    networks:
      - nginxReverse

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - nginx_reverse
      - docker-gen
      - nginx-proxy-letsencrypt
    environment:
      - VIRTUAL_HOST=nginx.doryhub.com
      - LETSENCRYPT_HOST=nginx.doryhub.com
      - LETSENCRYPT_EMAIL=garfield_trump@yahoo.com
    networks:
      - nginxReverse

networks:
  nginxReverse:
    driver: bridge
    name: nginx-reverse

